// aiService.js
// This file contains the AI service implementation

const axios = require('axios');
const ChatLog = require('./models/ChatLog');
const { getSpecializedPrompt } = require('./aiPrompts');

/**
 * Format the AI response for better readability in Telegram
 * @param {string} response - The raw AI response
 * @returns {string} - The formatted response
 */
function formatResponse(response) {
  // Add emojis to common sections
  let formatted = response
    .replace(/^# (.*)/gm, '🔹 *$1*') // Headers
    .replace(/^## (.*)/gm, '📌 *$1*') // Subheaders
    .replace(/^### (.*)/gm, '💡 *$1*') // Sub-subheaders
    .replace(/^\- (.*)/gm, '• $1') // List items
    .replace(/^\d+\. (.*)/gm, '🔸 $1') // Numbered lists
    .replace(/`([^`]+)`/g, '`$1`') // Code blocks
    .replace(/```([^`]+)```/g, '```$1```'); // Multi-line code blocks
  
  // Add a footer if the response is long
  if (formatted.length > 500) {
    formatted += '\n\n_This response was generated by AI. For more information, use /help_';
  }
  
  return formatted;
}

/**
 * Call the AI API to get a response
 * @param {string} userMessage - The user's message
 * @param {string} chatId - The chat ID
 * @param {string} openRouterApiKey - The OpenRouter API key
 * @param {string} huggingfaceApiKey - The Hugging Face API key
 * @returns {Promise<string>} - The AI response
 */
async function callAiApi(userMessage, chatId, openRouterApiKey, huggingfaceApiKey) {
  try {
    console.log("Calling OpenRouter...");
    
    // Get conversation history from the database
    let conversationHistory = [];
    try {
      const recentChats = await ChatLog.find({ 
        chatId: chatId 
      })
      .sort({ timestamp: -1 })
      .limit(5);
      
      if (recentChats && recentChats.length > 0) {
        conversationHistory = recentChats.reverse().map(chat => ({
          role: chat.isBot ? "assistant" : "user",
          content: chat.message
        }));
      }
    } catch (err) {
      console.error("Error fetching conversation history:", err);
    }
    
    // Get specialized prompt based on the question
    const systemPrompt = getSpecializedPrompt(userMessage);

    // Add a user-friendly instruction to the system prompt
    const enhancedSystemPrompt = `${systemPrompt}

IMPORTANT INSTRUCTIONS:
1. Format your response with Markdown for better readability
2. Use emojis sparingly to make your response more engaging
3. Keep your response concise but informative
4. If the question is complex, break it down into sections
5. For code examples, use proper code blocks with language specification
6. If you're not sure about something, be honest about it
7. End your response with a brief summary or conclusion`;

    const messages = [
      { role: "system", content: enhancedSystemPrompt },
      ...conversationHistory,
      { role: "user", content: userMessage }
    ];

    // Try to use a more advanced model first
    try {
      const response = await axios.post(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          model: "anthropic/claude-3-opus", // Using Claude 3 Opus as primary model
          messages: messages,
          temperature: 0.7,
          max_tokens: 1500,
          top_p: 0.9,
          frequency_penalty: 0.3,
          presence_penalty: 0.3
        },
        {
          headers: {
            Authorization: `Bearer ${openRouterApiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://your-site-url.com",
            "X-Title": "Telegram Bot",
          },
        }
      );

      const aiResponse = response.data.choices[0].message.content;
      
      // Log the conversation for history (only once)
      try {
        // Log user message
        await ChatLog.create({
          chatId: chatId,
          message: userMessage,
          isBot: false,
          timestamp: new Date()
        });
        
        // Log AI response
        await ChatLog.create({
          chatId: chatId,
          message: aiResponse,
          isBot: true,
          timestamp: new Date()
        });
      } catch (err) {
        console.error("Error logging conversation:", err);
      }

      // Format the response for better readability
      return formatResponse(aiResponse);
    } catch (primaryErr) {
      console.error("Primary model failed:", primaryErr.message);
      
      // Fallback to GPT-3.5 Turbo
      const fallbackResponse = await axios.post(
        "https://openrouter.ai/api/v1/chat/completions",
        {
          model: "openai/gpt-3.5-turbo",
          messages: messages,
          temperature: 0.7,
          max_tokens: 1000,
          top_p: 0.9,
          frequency_penalty: 0.3,
          presence_penalty: 0.3
        },
        {
          headers: {
            Authorization: `Bearer ${openRouterApiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://your-site-url.com",
            "X-Title": "Telegram Bot",
          },
        }
      );
      
      const aiResponse = fallbackResponse.data.choices[0].message.content;
      
      // Log fallback conversation (only once)
      try {
        // Log user message
        await ChatLog.create({
          chatId: chatId,
          message: userMessage,
          isBot: false,
          timestamp: new Date()
        });
        
        // Log AI response
        await ChatLog.create({
          chatId: chatId,
          message: aiResponse,
          isBot: true,
          timestamp: new Date()
        });
      } catch (err) {
        console.error("Error logging fallback conversation:", err);
      }
      
      return formatResponse(aiResponse);
    }
  } catch (err) {
    console.error("OpenRouter failed:", err.message);
    try {
      // Try Hugging Face as last resort
      const hfResponse = await axios.post(
        "https://api-inference.huggingface.co/models/google/flan-t5-xxl",
        { inputs: userMessage },
        {
          headers: {
            Authorization: `Bearer ${huggingfaceApiKey}`,
            "Content-Type": "application/json",
          },
        }
      );
      const response = hfResponse.data[0]?.generated_text || "⚠️ No response from Hugging Face.";
      
      // Log Hugging Face conversation (only once)
      try {
        // Log user message
        await ChatLog.create({
          chatId: chatId,
          message: userMessage,
          isBot: false,
          timestamp: new Date()
        });
        
        // Log AI response
        await ChatLog.create({
          chatId: chatId,
          message: response,
          isBot: true,
          timestamp: new Date()
        });
      } catch (err) {
        console.error("Error logging Hugging Face conversation:", err);
      }
      
      return formatResponse(response);
    } catch (hfError) {
      console.error("Hugging Face failed too:", hfError.message);
      return "❌ All AI services failed. Please try again later.";
    }
  }
}

module.exports = { callAiApi }; 